bucket_prefix = "devops-directive-web-app-data"
domain        = "devopsdeployed.com"
db_name       = "mydb"
db_user       = "foo"
db_pass = "SuperSecurePassword"
instance_type = "t3.small"
db_instance_type = "db.t3.small"